#if 0
#define DEBUG
#define WPRINT_ENABLE_LIB_INFO          1
#define WPRINT_ENABLE_LIB_DEBUG 1
#define WPRINT_ENABLE_LIB_ERROR 1
#define WPRINT_ENABLE_WEBSERVER_INFO            1
#define WPRINT_ENABLE_WEBSERVER_DEBUG 1
#define WPRINT_ENABLE_WEBSERVER_ERROR 1
#define WPRINT_ENABLE_APP_INFO          1
#define WPRINT_ENABLE_APP_DEBUG 1
#define WPRINT_ENABLE_APP_ERROR 1
#define WPRINT_ENABLE_NETWORK_INFO          1
#define WPRINT_ENABLE_NETWORK_DEBUG 1
#define WPRINT_ENABLE_NETWORK_ERROR 1
#define WPRINT_ENABLE_RTOS_INFO         1
#define WPRINT_ENABLE_RTOS_DEBUG 1
#define WPRINT_ENABLE_RTOS_ERROR 1
#define WPRINT_ENABLE_SECURITY_INFO         1
#define WPRINT_ENABLE_SECURITY_DEBUG 1
#define WPRINT_ENABLE_SECURITY_ERROR 1
#define WPRINT_ENABLE_WPS_INFO          1
#define WPRINT_ENABLE_WPS_DEBUG 1
#define WPRINT_ENABLE_WPS_ERROR 1
#define WPRINT_ENABLE_SUPPLICANT_INFO           1
#define WPRINT_ENABLE_SUPPLICANT_DEBUG 1
#define WPRINT_ENABLE_SUPPLICANT_ERROR 1
#define WPRINT_ENABLE_PLATFORM_INFO         1
#define WPRINT_ENABLE_PLATFORM_DEBUG 1
#define WPRINT_ENABLE_PLATFORM_ERROR 1
#define WPRINT_ENABLE_WICED_INFO            1
#define WPRINT_ENABLE_WICED_DEBUG 1
#define WPRINT_ENABLE_WICED_ERROR 1
#define WPRINT_ENABLE_WWD_INFO          1
#define WPRINT_ENABLE_WWD_DEBUG 1
#define WPRINT_ENABLE_WWD_ERROR 1
#endif